os: linux
language: python
python: "3.7"
dist: bionic
compiler:
  - gcc
install:
# Install conan
  - pip install conan
  - conan user

before_script:
  - conan install . -pr .travis/native --build=missing

script:
  - conan build .
  - source activate.sh
  - ctest .
