matrix:
  include:
    - os: linux
      language: python
      python: "3.7"
      dist: bionic
      compiler: gcc
      env:
        - CONAN_PROFILE=.travis/native

    - os: linux
      language: python
      python: "3.7"
      dist: bionic
      compiler:
          - gcc
          - clang 
      env:
        - CONAN_PROFILE=.travis/wasm

    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3 --version 3.7
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      env:
        - CONAN_PROFILE=.travis/native


install:
  - pip install conan
  - conan user

before_script:
  # not nice. Improve in general the build for both native and wasm
  - if [[ "${CONAN_PROFILE}" == '.travis/wasm' ]]; then
    conan install Parsing/ --build=missing ;
    fi
  - conan install . -pr ${CONAN_PROFILE} --build=missing

script:
  - conan build .
  - source activate.sh
  # Do not execute for the moment the test in wasm
  - if [[ "${CONAN_PROFILE}" != '.travis/wasm' ]]; then
    ctest . ;
    fi