matrix:
  include:
    - os: linux
      language: python
      python: "3.7"
      dist: bionic
      compiler: gcc
      env:
        - CONAN_PROFILE=.travis/linux

    - os: linux
      language: python
      python: "3.7"
      dist: bionic
      compiler: clang
      env:
        - CONAN_PROFILE=.travis/wasm

    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3 --version 3.7
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      env:
        - CONAN_PROFILE=.travis/windows


install:
  - pip install conan
  - conan user

before_script:
  # For compiling wasm we have to already have Expat as a native library
  - if [[ "${CONAN_PROFILE}" == '.travis/wasm' ]]; then
    conan install Expat/2.2.9@pix4d/stable --build=missing;
    fi
  - conan install . -pr ${CONAN_PROFILE} --build=missing

script:
  - conan build .
  - source activate.sh
  # Execute for the moment the UT only in Linux
  - if [[ "${CONAN_PROFILE}" == '.travis/linux' ]]; then
    ctest . ;
    fi