# https://github.com/conan-io/conan-package-tools
# Maybe to use in the future

matrix:
  include:
    - name: "Linux build with pre-install Cmake"
      os: linux
      language: python
      python: "3.7"
      dist: bionic
      compiler: gcc
      cache:
        pip: true
      addons:
        apt:
          sources:
          # Official Kitware APT repository.
          # More information at: https://apt.kitware.com
          - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
            key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
          packages:
          - cmake
      env:
        - CONAN_PROFILE=

    - name: "Linux build with conan"
      os: linux
      language: python
      python: "3.7"
      dist: bionic
      compiler: gcc
      cache:
        pip: true
      env:
        - CONAN_PROFILE=linux
    
    - name: "Wasm build"
      os: linux
      language: python
      python: "3.7"
      dist: bionic
      compiler: gcc
      cache:
        pip: true
      env:
        - CONAN_PROFILE=wasm
    
    - name: "Windows build with conan"
      os: windows
      language: sh
      python: "3.7"
      cache:
        directories:
          - $HOME/AppData/Local/Temp/chocolatey
      before_install:
        - choco install python3 --version 3.7
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      env:
        - CONAN_PROFILE=windows


install:
  - pip install conan
  - conan user

script:
  # Building using conan
  - if [ -n "${CONAN_PROFILE}" ]; then
    conan create --profile:build=.travis/${TRAVIS_OS_NAME}_build --profile:host=.travis/${CONAN_PROFILE}_host --build=missing -tf tests . user/testing;
    fi

  # Building by calling conan via the Cmake. These are 2 differents builds. 
  # If no conan profile is provided then we use this method
  # Not the best, but for the moment it will have to be sufficient
  - if [ -z "${CONAN_PROFILE}" ]; then
    /usr/bin/cmake . -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=TRUE -DUSE_SQLITE3=TRUE;
    fi
  - if [ -z "${CONAN_PROFILE}" ]; then
    make;
    fi
  - if [ -z "${CONAN_PROFILE}" ]; then
    ctest . ;
    fi